# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？ 数据类型：布尔类型、浮点型、整型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [2]:
start = 1
sum = 0
while start <100:
    temp = start % 2
    if temp ==1:
        sum = sum + start
    else:
        sum = sum - start
    #print(start)
    #sum = sum + 1
    start += 1
print(sum)

50


1.3  将字符串 s="yoyo" 转换成列表

In [4]:
s = 'yoyo'
list(s)

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的
 输出1~100之间的随机数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [21]:
class time:
    def __init__(self,time, high, close):
        self.time=time
        self.high = high
        self.close = close
    def calAmount(self):
        return {self.time+'_dif': self.high-self.close}

time_one = time('one',15,7)
print(time_one.calAmount())

time_two = time('two',66,20)
print(time_two.calAmount())


{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [27]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(5,4),columns = ['a','b','c','d'])
print(df)
print(df.columns)

          a         b         c         d
0  2.057946 -0.746313  0.580325 -1.825733
1 -0.507424  0.740034  1.092616  0.045911
2  0.664235  2.828097 -0.347350  1.156929
3  0.736373  0.557447  1.389310 -0.363879
4 -0.266433  0.910271  0.442494 -0.400553
Index(['a', 'b', 'c', 'd'], dtype='object')


In [28]:
df.transpose()

0         1         2         3         4
a  2.057946 -0.507424  0.664235  0.736373 -0.266433
b -0.746313  0.740034  2.828097  0.557447  0.910271
c  0.580325  1.092616 -0.347350  1.389310  0.442494
d -1.825733  0.045911  1.156929 -0.363879 -0.400553

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [16]:
import numpy as np
import pandas as pd
import warnings
import talib as ta
warnings.filterwarnings('ignore')
data = pd.read_excel('sz50.xlsx',sheetname=None, index_col='datetime')

data['600029.XSHG']
MA = ta.EMA(data['600029.XSHG'].close.values, 10)
print(type(MA))
print(MA[-5:])

<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


<class 'numpy.ndarray'>
[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [17]:
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc['2017-03-21':'2017-05-10']
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 34 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-03-21 15:00:00 to 2017-05-10 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

(3, 215, 5)
[[  13.85   13.82   13.83   14.11   14.25   14.39   15.1    15.15   15.22
    14.97   14.89   14.99   14.71   15.07   15.35   16.     16.04   16.29
    16.97   17.05]
 [   8.53    8.56    8.62    8.88    9.25    9.24    9.43    9.25    9.02
     9.15    9.63    9.5     9.9     9.97    9.96    9.49    9.68    9.61
     9.63    9.8 ]
 [ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
   143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
   168.58  169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [25]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
arr2 = np.arange(25).reshape(5,5)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
